#!/bin/bash

SKIP_COMMITIZEN=$(ps -ocommand= -p $PPID | grep -e '--amend' -e 'rebase' -e 'cherry-pick' | xargs echo -n);

if [ -z "$SKIP_COMMITIZEN" ] && [ "$HUSKY" != "0" ]; then
  exec < /dev/tty && yarn cz --hook || true
fi
