name: CI - Pull Request

env:
  NODE_ENV: development
  NX_CLOUD_AUTH_TOKEN: ${{ secrets.NX_CLOUD_AUTH_TOKEN }}
  NX_CLOUD_DISTRIBUTED_EXECUTION: true
  CI: true
  CYPRESS_CACHE_FOLDER: ./.cache/Cypress

on:
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  agents:
    uses: ./.github/workflows/nx-agents.yml
    secrets:
      nxCloudToken: ${{ secrets.NX_CLOUD_AUTH_TOKEN }}

  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - uses: ./.github/actions/install-dependencies

      - uses: ./.github/actions/set-nx-cloud
        with:
          operation: start

      - name: Lint code
        run: yarn ci:lint

      - name: Lint styles
        run: yarn ci:stylelint

  testing:
    name: Testing
    runs-on: ubuntu-latest
    needs:
      - linting
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - uses: ./.github/actions/install-dependencies

      - uses: ./.github/actions/set-nx-cloud
        with:
          operation: start

      - name: Run unit tests
        run: yarn ci:test

      - name: Run e2e tests
        run: yarn ci:e2e

  building:
    name: Building
    runs-on: ubuntu-latest
    needs:
      - testing
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - uses: ./.github/actions/install-dependencies

      - uses: ./.github/actions/set-nx-cloud
        with:
          operation: start

      - name: Build
        run: yarn ci:build

  cleanup:
    name: Cleanup
    runs-on: ubuntu-latest
    continue-on-error: true
    if: always()
    needs:
      - testing
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Stop Nx Agents
        uses: ./.github/actions/set-nx-cloud
        with:
          operation: stop
